import type { PropType } from "vue";

export const commonProps = {
  id: [String, Number] as PropType<string | number>,
  left: [String, Number] as PropType<string | number>,
  right: [String, Number] as PropType<string | number>,
  top: [String, Number] as PropType<string | number>,
  bottom: [String, Number] as PropType<string | number>,
  width: [String, Number] as PropType<string | number>,
  height: [String, Number] as PropType<string | number>,
  rotation: Number,
  scaleX: Number,
  scaleY: Number,
  originX: Number,
  originY: Number,
  bounding: String,
  z: Number,
  zlevel: Number,
  silent: Boolean,
  draggable: [Boolean, String] as PropType<boolean | "horizontal" | "vertical">,
  cursor: String,
  ignore: Boolean,
  invisible: Boolean,
  info: null as unknown as PropType<unknown>,
  focus: String,
  blurScope: String,
  transition: [String, Array] as PropType<string | string[]>,
  enterFrom: Object as PropType<Record<string, unknown>>,
  leaveTo: Object as PropType<Record<string, unknown>>,
  enterAnimation: Object as PropType<Record<string, unknown>>,
  updateAnimation: Object as PropType<Record<string, unknown>>,
  leaveAnimation: Object as PropType<Record<string, unknown>>,
  keyframeAnimation: Object as PropType<Record<string, unknown>>,
  shape: Object as PropType<Record<string, unknown>>,
  style: Object as PropType<Record<string, unknown>>,
  shapeTransition: [String, Array] as PropType<string | string[]>,
  styleTransition: [String, Array] as PropType<string | string[]>,
  fill: String,
  stroke: String,
  lineWidth: Number,
  lineDash: [String, Array] as PropType<string | number[]>,
  lineDashOffset: Number,
  lineCap: String,
  lineJoin: String,
  miterLimit: Number,
  shadowBlur: Number,
  shadowOffsetX: Number,
  shadowOffsetY: Number,
  shadowColor: String,
  opacity: Number,
  blend: String,
  text: String,
  font: String,
  textFill: String,
  textStroke: String,
  textStrokeWidth: Number,
  textAlign: String,
  textVerticalAlign: String,
  textLineHeight: Number,
  textShadowBlur: Number,
  textShadowOffsetX: Number,
  textShadowOffsetY: Number,
  textShadowColor: String,
  image: [String, HTMLImageElement, HTMLCanvasElement, HTMLVideoElement] as PropType<
    string | HTMLImageElement | HTMLCanvasElement | HTMLVideoElement
  >,
} as const;
