name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.10
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
