name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"

permissions:
  contents: read

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.11
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
            RENOVATE_REPOSITORIES: ${{ github.repository }}
